ipfs-download-from:
  description: Choose the source to download IPFS data from
  variants:
  - kubo
  - cybernode
ipfs-storage:
  description: Choose the destination to upload IPFS data to
  variants:
  - kubo
  - cybernode
  - both
caching-function-force-update:
  description: Don't use cached node responses, update results immediately
  variants:
  - 'true'
  - 'false'
caching-function-max-retries:
  description: The maximum number of retries in case of an error response
  variants:
  - 5
  - 3
  - 1
authz:
  description: The address to send links from
  variants:
  - 'other'
